In [3]:
import numpy as np

In [4]:
a1=np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [4]:
type(a1) #it's an array

numpy.ndarray

In [5]:
a1.shape #gives the rows and columns. Since it's 1-D, giving only columns

(5,)

In [6]:
a1.ndim # gives the dimensions of the givne array

1

In [161]:
new_array=np.array(['a','b','c'])
new_array

array(['a', 'b', 'c'], dtype='<U1')

In [9]:
a1=np.array([[1,2,3],[4,5,6]])
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a1.shape

(2, 3)

In [11]:
a1=np.array([[1,2,3],[4,5,6]], dtype=float)
a1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [12]:
a1=a1.reshape(3,2) #Transpose
a1

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [16]:
a2=a1.reshape(2,5)
a2

ValueError: cannot reshape array of size 6 into shape (2,5)

In [17]:
a1=np.ones([2,2],dtype=float)
a1

array([[1., 1.],
       [1., 1.]])

In [20]:
x1=([3,2],[4,5],[6,7])
a1=np.asarray(x1,dtype=float)
a1

array([[3., 2.],
       [4., 5.],
       [6., 7.]])

In [21]:
a1=np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
type(a1)

numpy.ndarray

In [23]:
a1=np.linspace(10,20,5)
a1

array([10. , 12.5, 15. , 17.5, 20. ])

In [26]:
a1=np.linspace(1,10,15
              
              )
a1

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [5]:
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
a1[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [6]:
a1[...,1]

array([2, 5, 8])

In [8]:
a=np.array([[1,2],[3,4],[5,6]])
a
b=a[[0,1,2],[0,1,0]]
b

array([1, 4, 5])

In [9]:
a[a<3]

array([1, 2])

In [14]:
a=np.array([1.,3., np.nan, 4, np.nan])
a

array([ 1.,  3., nan,  4., nan])

In [15]:
a[~np.isnan(a)]

array([1., 3., 4.])

In [24]:
x=np.array([3,4,5])
y=np.array([2,3,4])
z=x*y
print(z)


[ 6 12 20]


In [32]:
x=np.array([3,4,5])
y=np.array([[2,3,5],[1,2,3]])
z=x*y
print(z)

b=2.5
z=b*x
print(z)
c=y.T #Transpose the given array
print(c)



[[ 6 12 25]
 [ 3  8 15]]
[ 7.5 10.  12.5]
[[2 1]
 [3 2]
 [5 3]]


In [ ]:
#faltten : makes ebverything as one array

In [35]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[11,22,33],[44,55,66]])

np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 22, 33],
       [44, 55, 66]])

In [36]:
np.concatenate((a,b),axis=1)

array([[ 1,  2,  3, 11, 22, 33],
       [ 4,  5,  6, 44, 55, 66]])

In [40]:
del sum1

In [41]:
np.stack((a,b))

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 22, 33],
        [44, 55, 66]]])

In [50]:
np.stack((a,b),axis=1)

array([[[ 1,  2,  3],
        [11, 22, 33]],

       [[ 4,  5,  6],
        [44, 55, 66]]])

In [47]:
np.hstack((a,b))
#Shape changes but not the dimensions

array([[ 1,  2,  3, 11, 22, 33],
       [ 4,  5,  6, 44, 55, 66]])

In [55]:
np.vstack((a,b))
print(a.shape)
print(b.shape)
c=np.vstack((a,b))
print(c)
d=c.shape
print(d)

(2, 3)
(2, 3)
[[ 1  2  3]
 [ 4  5  6]
 [11 22 33]
 [44 55 66]]
(4, 3)


In [57]:
sp=np.arange(9)
np.split(sp,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [63]:
a1=np.array([[10,20,30],[40,50,60]])
np.append(a1,[[1,2,3]],axis=0)

array([[10, 20, 30],
       [40, 50, 60],
       [ 1,  2,  3]])

In [67]:
np.append(a1,[[1,2,3],[4,5,6]],axis=1)

array([[10, 20, 30,  1,  2,  3],
       [40, 50, 60,  4,  5,  6]])

In [71]:
np.insert(a1,1,[7],axis=0)

array([[10, 20, 30],
       [ 7,  7,  7],
       [40, 50, 60]])

In [69]:
np.insert(a1,1,[9],axis=1)

array([[10,  9, 20, 30],
       [40,  9, 50, 60]])

In [78]:
a1=np.array([[10,20,30],[40,50,60]])
np.insert(a1,1,[7,8,9],axis=0)

array([[10, 20, 30],
       [ 7,  8,  9],
       [40, 50, 60]])

In [95]:
a3=np.arange(12).reshape(3,4)
print(a3)
np.delete(a3,0,axis=0)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
np.delete(a3,3,axis=1)

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [92]:
np.unique(a3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [100]:
a=np.arange(9,dtype=float).reshape(3,3)
b=np.array([1,2,3])
a


array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [99]:
np.add(a,b)

array([[ 1.,  3.,  5.],
       [ 4.,  6.,  8.],
       [ 7.,  9., 11.]])

In [101]:
np.subtract(a,b)

array([[-1., -1., -1.],
       [ 2.,  2.,  2.],
       [ 5.,  5.,  5.]])

In [102]:
np.multiply(a,b)

array([[ 0.,  2.,  6.],
       [ 3.,  8., 15.],
       [ 6., 14., 24.]])

In [103]:
np.divide(a,b)

array([[0.        , 0.5       , 0.66666667],
       [3.        , 2.        , 1.66666667],
       [6.        , 3.5       , 2.66666667]])

In [104]:
np.remainder(a,b)

array([[0., 1., 2.],
       [0., 0., 2.],
       [0., 1., 2.]])

In [105]:
    np.power(a,3)

array([[  0.,   1.,   8.],
       [ 27.,  64., 125.],
       [216., 343., 512.]])

In [111]:
#percentile for ranking

a=np.array([[10,40,70],[20,35,75],[20,50,60]])
print (a)
print(np.percentile(a,100,axis=0))
print(np.percentile(a,50,axis=1))



[[10 40 70]
 [20 35 75]
 [20 50 60]]
[20. 50. 75.]
[40. 35. 50.]


In [112]:
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

[16.66666667 41.66666667 68.33333333]
[40.         43.33333333 43.33333333]


In [113]:
import pandas as pd

In [114]:
a=np.array([1,2,3,4])
s=pd.Series(a)
s

0    1
1    2
2    3
3    4
dtype: int32

In [115]:
my_dict={'a':1,'b':2,'c':3}
s_dict=pd.Series(my_dict)
s_dict

a    1
b    2
c    3
dtype: int64

In [121]:
s=pd.Series(a, index=[10,20,30,40]) #index should match the no of elements
s

10    1
20    2
30    3
40    4
dtype: int32

In [122]:
type(s)

pandas.core.series.Series

In [123]:
s=pd.Series(my_dict,index=['a','b','c','d']) #Added Index, gives the vale as NaN
s

a    1.0
b    2.0
c    3.0
d    NaN
dtype: float64

In [124]:
s[2]

3.0

In [127]:
s[:2]

a    1.0
b    2.0
dtype: float64

In [128]:
s['b']

2.0

In [129]:
df1=pd.DataFrame()
print(df1)

Empty DataFrame
Columns: []
Index: []


In [130]:
ldf=list(range(5)) #Create a dataFrame from a list
df1=pd.DataFrame(ldf)
df1

0
0  0
1  1
2  2
3  3
4  4

my_list1=[['A',10],['B',20],['C',30]]
df2=pd.DataFrame(my_list1,column)

In [131]:
my_list1=[['A',10],['B',20],['C',30]]
df2=pd.DataFrame(my_list1,columns=['First','Second'],dtype=float)
df2

First  Second
0     A    10.0
1     B    20.0
2     C    30.0

In [166]:
my_dict1={'Name':['aaa','bbb','ccc'], 'Age':[25,26,27]}
my_df2=pd.DataFrame(my_dict1)
my_df2


Name  Age
0  aaa   25
1  bbb   26
2  ccc   27

In [163]:
df['Height']=pd.Series([150,160,170],index=[1,2,3])
df['Add']=df['Age']+df['Height']
df


Name  Age  Height    Add
0  aaa   25     NaN    NaN
1  bbb   26   150.0  176.0
2  ccc   27   160.0  187.0

In [150]:
my_df2['Height']=pd.Series([150,160,170],index=[1,2,3])
my_df2['Add']=my_df2['Age']+my_df2['Height']
my_df2

Name  Age  Height    Add
0  aaa   25     NaN    NaN
1  bbb   26   150.0  176.0
2  ccc   27   160.0  187.0

In [180]:
my_df2.drop(['Add'],axis=1,inplace=True)
my_df2

Name  Age  Height
a  aaa   25     150
b  bbb   26     160
c  ccc   27     170

In [145]:
my_df2=my_df2.drop(['Name'],1)

In [148]:
my_df2

Age  Height
0   25     NaN
1   26   150.0
2   27   160.0

In [153]:
my_df2.drop(['Age'],0)

KeyError: "['Age'] not found in axis"

In [155]:
my_df2

Name  Age  Height
0  aaa   25     NaN
1  bbb   26   150.0
2  ccc   27   160.0

In [156]:
my_df2.index=['a','b','c']
my_df2

Name  Age  Height
a  aaa   25     NaN
b  bbb   26   150.0
c  ccc   27   160.0

In [157]:
my_df2.loc['b']

Name      bbb
Age        26
Height    150
Name: b, dtype: object

In [167]:
my_df2['Height']=pd.Series([150,160,170],index=[0,1,2])
my_df2['Add']=my_df2['Age']+my_df2['Height']
my_df2

Name  Age  Height  Add
0  aaa   25     150  175
1  bbb   26     160  186
2  ccc   27     170  197

In [168]:
my_df2.loc[:,'Age']

0    25
1    26
2    27
Name: Age, dtype: int64

In [170]:
my_df2.index=['a','b','c']

In [176]:
my_df2.loc['c',['Height','Age']]

Height    170
Age        27
Name: c, dtype: object

In [175]:
my_df2.loc[['a','b'],['Height','Age']]

Height  Age
a     150   25
b     160   26

In [177]:
my_df2.iloc[1] #INdex based search

Name      bbb
Age        26
Height    160
Add       186
Name: b, dtype: object

In [182]:
my_df2.loc[-1]=['ddd',30,180]
my_df2 #Without index mentioning, added as new index -1

Name  Age  Height
a   aaa   25     150
b   bbb   26     160
c   ccc   27     170
-1  ddd   30     180

In [183]:
my_df2.index=['a','b','c','d']
my_df2

Name  Age  Height
a  aaa   25     150
b  bbb   26     160
c  ccc   27     170
d  ddd   30     180

In [187]:
my_df2[:1]

Name  Age  Height
a  aaa   25     150

In [188]:
#Row Addition

In [189]:
my_df2.loc[my_df2['Age']>26,:]

Name  Age  Height
c  ccc   27     170
d  ddd   30     180

In [194]:
#Row addtion with append operator

df1=pd.DataFrame([[1,2],[3,4]],columns=['a','b'])
df2=pd.DataFrame([[5,6],[7,8]],columns=['a','b'])

df3=df1.append(df2)
#df3.index=[0,1,2,3]
df3.resetIndex()
df3


AttributeError: 'DataFrame' object has no attribute 'resetIndex'

In [195]:
dic1={'Name':pd.Series(['Jack','Jones','Bat','Cast','Doorth','Steve']),
     'Age':pd.Series([24,23,26,21,30,25]),
     'Rating':pd.Series([3,6,2,7,4,9])}

df3=pd.DataFrame(dic1)
df3

Name  Age  Rating
0    Jack   24       3
1   Jones   23       6
2     Bat   26       2
3    Cast   21       7
4  Doorth   30       4
5   Steve   25       9

In [196]:
df3.head() #Displays first 5 records in the frame

Name  Age  Rating
0    Jack   24       3
1   Jones   23       6
2     Bat   26       2
3    Cast   21       7
4  Doorth   30       4

In [197]:
df3.tail #Displays the last 5 records in the frame

Name  Age  Rating
1   Jones   23       6
2     Bat   26       2
3    Cast   21       7
4  Doorth   30       4
5   Steve   25       9

df.T

In [198]:
df3.T #Transpose of the dataframe

0      1    2     3       4      5
Name    Jack  Jones  Bat  Cast  Doorth  Steve
Age       24     23   26    21      30     25
Rating     3      6    2     7       4      9

In [199]:
df3.axes #Displays the Index and their range

[RangeIndex(start=0, stop=6, step=1),
 Index(['Name', 'Age', 'Rating'], dtype='object')]

In [200]:
df3.dtypes #Displays the dataType

Name      object
Age        int64
Rating     int64
dtype: object

In [201]:
df3.empty #Checks if empty

False

In [202]:
df3.shape #Dimensions of the Frame

(6, 3)

In [203]:
df3.size

18

In [ ]:
#Basic Statsitical functions in Panda

In [205]:
df3

Name  Age  Rating
0    Jack   24       3
1   Jones   23       6
2     Bat   26       2
3    Cast   21       7
4  Doorth   30       4
5   Steve   25       9

In [204]:
df3.sum()

Name      JackJonesBatCastDoorthSteve
Age                               149
Rating                             31
dtype: object

In [206]:
df3.sum(1) #Adds based on the column basis

0    27
1    29
2    28
3    28
4    34
5    34
dtype: int64

In [208]:
df3.sum(axis=1) #Same as above

0    27
1    29
2    28
3    28
4    34
5    34
dtype: int64

In [209]:
df3.mean()

Age       24.833333
Rating     5.166667
dtype: float64

In [210]:
df3.median()

Age       24.5
Rating     5.0
dtype: float64

In [211]:
#mode : Frequency of the number
df3['Age'].mode()

0    21
1    23
2    24
3    25
4    26
5    30
dtype: int64

In [212]:
df3['Name'].mode()

0       Bat
1      Cast
2    Doorth
3      Jack
4     Jones
5     Steve
dtype: object

In [214]:
df3['Age'].min()

21

In [215]:
df3.describe()

Age    Rating
count   6.000000  6.000000
mean   24.833333  5.166667
std     3.060501  2.639444
min    21.000000  2.000000
25%    23.250000  3.250000
50%    24.500000  5.000000
75%    25.750000  6.750000
max    30.000000  9.000000

In [219]:
dict2={'Col1':[10,20,30,40],
      'Col2':[23,45,34,29],
       'Col3':[34,45,30,40]}
df4=pd.DataFrame(dict2)
df4

Col1  Col2  Col3
0    10    23    34
1    20    45    45
2    30    34    30
3    40    29    40

In [222]:
df4.apply(np.mean) #We can use lampda function also in the apply

Col1    25.00
Col2    32.75
Col3    37.25
dtype: float64

In [227]:
df4.apply(lambda x:x.max()-x.min())

Col1    30
Col2    22
Col3    15
dtype: int64

In [229]:
df4.apply(lambda x:x.max()-x.min(),axis=1)

0    24
1    25
2     4
3    11
dtype: int64

In [231]:
df3.rename(columns={'Name':'Col1','Age':'Col2','Rating':'Col3'}) #Only displaying here. Dataframe=assignment to be chnaged in the actual dataframe

Col1  Col2  Col3
0    Jack    24     3
1   Jones    23     6
2     Bat    26     2
3    Cast    21     7
4  Doorth    30     4
5   Steve    25     9

In [232]:
df5=pd.DataFrame(np.random.randn(5,2),index=[1,5,4,3,2],columns=['Col1','Col2']) #Generate random data from the Random function
df5

Col1      Col2
1  1.008452 -1.554769
5 -0.172915  0.313117
4  0.739971  1.258912
3  0.129252 -0.526588
2  0.412043  1.133500

In [233]:
df5.sort_index()

Col1      Col2
1  1.008452 -1.554769
2  0.412043  1.133500
3  0.129252 -0.526588
4  0.739971  1.258912
5 -0.172915  0.313117

In [234]:
df5.sort_index(ascending=False)

Col1      Col2
5 -0.172915  0.313117
4  0.739971  1.258912
3  0.129252 -0.526588
2  0.412043  1.133500
1  1.008452 -1.554769

In [235]:
df5.sort_index(axis=1)

Col1      Col2
1  1.008452 -1.554769
5 -0.172915  0.313117
4  0.739971  1.258912
3  0.129252 -0.526588
2  0.412043  1.133500

In [236]:
df5.sort_values(by='Col1')

Col1      Col2
5 -0.172915  0.313117
3  0.129252 -0.526588
2  0.412043  1.133500
4  0.739971  1.258912
1  1.008452 -1.554769

In [237]:
df5.sort_values(by='Col2',ascending=False)

Col1      Col2
4  0.739971  1.258912
2  0.412043  1.133500
5 -0.172915  0.313117
3  0.129252 -0.526588
1  1.008452 -1.554769

In [238]:
df3.loc[:3,['Age','Rating']]

Age  Rating
0   24       3
1   23       6
2   26       2
3   21       7

In [239]:
df3.loc[:2]

Name  Age  Rating
0   Jack   24       3
1  Jones   23       6
2    Bat   26       2

In [240]:
df3

Name  Age  Rating
0    Jack   24       3
1   Jones   23       6
2     Bat   26       2
3    Cast   21       7
4  Doorth   30       4
5   Steve   25       9

In [241]:
df3.index=['a','b','c','d','e','f']

In [242]:
df3.loc['a':'e']

Name  Age  Rating
a    Jack   24       3
b   Jones   23       6
c     Bat   26       2
d    Cast   21       7
e  Doorth   30       4

In [243]:
df3.iloc[0:2,1:2]

Age
a   24
b   23

In [245]:
df3.iloc[:,1:] # all rows and from the column index=1

Age  Rating
a   24       3
b   23       6
c   26       2
d   21       7
e   30       4
f   25       9

In [248]:
df6=pd.DataFrame(np.random.randn(5,3),index=['a','c','e','f','h'],columns=['one','two','three'])
df6=df6.reindex(['a','b','c','d','e','f','g','h'])
df6

one       two     three
a  1.229101 -2.095960 -1.957946
b       NaN       NaN       NaN
c -0.881188  0.213861  1.201003
d       NaN       NaN       NaN
e -0.800761 -1.357747 -0.504813
f -0.280844 -1.541685 -1.063269
g       NaN       NaN       NaN
h -0.348708  1.977881  0.145156

In [250]:
df6['one'].isnull()

a    False
b     True
c    False
d     True
e    False
f    False
g     True
h    False
Name: one, dtype: bool

In [254]:
df6['one'].isna() #this and isnull() gives the same output

a    False
b     True
c    False
d     True
e    False
f    False
g     True
h    False
Name: one, dtype: bool

In [255]:
df6['two'].notnull()

a     True
b    False
c     True
d    False
e     True
f     True
g    False
h     True
Name: two, dtype: bool

In [256]:
df6['three'].isnull().sum()

3

In [257]:
df6['one'].fillna(0)

a    1.229101
b    0.000000
c   -0.881188
d    0.000000
e   -0.800761
f   -0.280844
g    0.000000
h   -0.348708
Name: one, dtype: float64

In [258]:
df6

one       two     three
a  1.229101 -2.095960 -1.957946
b       NaN       NaN       NaN
c -0.881188  0.213861  1.201003
d       NaN       NaN       NaN
e -0.800761 -1.357747 -0.504813
f -0.280844 -1.541685 -1.063269
g       NaN       NaN       NaN
h -0.348708  1.977881  0.145156

In [261]:
df6.fillna(1,inplace=True)

In [262]:
df6

one       two     three
a  1.229101 -2.095960 -1.957946
b  1.000000  1.000000  1.000000
c -0.881188  0.213861  1.201003
d  1.000000  1.000000  1.000000
e -0.800761 -1.357747 -0.504813
f -0.280844 -1.541685 -1.063269
g  1.000000  1.000000  1.000000
h -0.348708  1.977881  0.145156

In [273]:
df6.loc['d':'f']=pd.Series([{'one':np.NAN,'two':np.NAN,'three':np.NAN}]) #Have a check

In [274]:
df6

one       two     three
a  1.229101 -2.095960 -1.957946
b  1.000000  1.000000  1.000000
c -0.881188  0.213861  1.201003
d       NaN       NaN       NaN
e       NaN       NaN       NaN
f       NaN       NaN       NaN
g  1.000000  1.000000  1.000000
h -0.348708  1.977881  0.145156

In [277]:
df6.dropna(inplace=True)

In [278]:
df6

one       two     three
a  1.229101 -2.095960 -1.957946
b  1.000000  1.000000  1.000000
c -0.881188  0.213861  1.201003
g  1.000000  1.000000  1.000000
h -0.348708  1.977881  0.145156

In [266]:
df7=pd.DataFrame({'one':[10,20,30,40,50000],'two':[1000,15,2,5,35]})
df7

one   two
0     10  1000
1     20    15
2     30     2
3     40     5
4  50000    35

In [267]:
df7.replace({50000:50,1000:10})

one  two
0   10   10
1   20   15
2   30    2
3   40    5
4   50   35

In [268]:
df7

one   two
0     10  1000
1     20    15
2     30     2
3     40     5
4  50000    35

In [269]:
df7.replace({50000:50,1000:10},inplace=True)

In [267]:
df7.replace({50000:50,1000:10})

one  two
0   10   10
1   20   15
2   30    2
3   40    5
4   50   35

In [270]:
df7

one  two
0   10   10
1   20   15
2   30    2
3   40    5
4   50   35

In [283]:
df3

Name  Age  Rating  Score
a    Jack   25       3     70
b   Jones   21       6     30
c     Bat   26       2     40
d    Cast   21       7     50
e  Doorth   30       4     70
f   Steve   25       9     80

In [280]:
df3.replace({24:25,23:21},inplace=True)

In [282]:
df3['Score']=pd.Series([70,30,40,50,70,80], index=['a','b','c','d','e','f'])

In [285]:
df3.groupby(['Age']
           )['Score'].sum()

Age
21     80
25    150
26     40
30     70
Name: Score, dtype: int64

In [286]:
df3.groupby(['Age'])['Rating','Score'].mean().reset_index()

Age  Rating  Score
0   21     6.5   40.0
1   25     6.0   75.0
2   26     2.0   40.0
3   30     4.0   70.0

In [288]:
df3.groupby(['Name'])['Age'].sum()

Name
Bat       26
Cast      21
Doorth    30
Jack      25
Jones     21
Steve     25
Name: Age, dtype: int64

In [289]:
df3.groupby(['Age'])['Rating','Score'].agg([np.median,np.mean,np.std]).reset_index()

Age Rating                 Score                
      median mean       std median mean        std
0  21    6.5  6.5  0.707107     40   40  14.142136
1  25    6.0  6.0  4.242641     75   75   7.071068
2  26    2.0  2.0       NaN     40   40        NaN
3  30    4.0  4.0       NaN     70   70        NaN

In [298]:
df_left=pd.DataFrame({'id':[1,2,3,4,5],
                     'Name':['Alex','Amy','Allen','Alice','Adam'],
                     'subject_id':['sub1','sub2','sub4','sub6','sub5']})

df_right=pd.DataFrame({'id':[1,2,3,4,5],
                     'Name':['Billy','Brain','Brad','Bruce','Betty'],
                     'subject_id':['sub2','sub4','sub3','sub6','sub5']})

df_right1=pd.DataFrame({'id':[1,2,3,4,5],
                     'Name':['Cath','Cool','Chris','Crain','Case'],
                     'subject_id':['sub2','sub1','sub2','sub6','sub3']})

In [299]:
df_right1

id   Name subject_id
0   1   Cath       sub2
1   2   Cool       sub1
2   3  Chris       sub2
3   4  Crain       sub6
4   5   Case       sub3

In [294]:
df_left

id   Name subject_id
0   1   Alex       sub1
1   2    Amy       sub2
2   3  Allen       sub4
3   4  Alice       sub6
4   5   Adam       sub5

In [295]:
df_right

id   Name subject_id
0   1  Billy       sub2
1   2  Brain       sub4
2   3   Brad       sub3
3   4  Bruce       sub6
4   5  Betty       sub5

In [296]:
pd.merge(df_left,df_right,on='id')

id Name_x subject_id_x Name_y subject_id_y
0   1   Alex         sub1  Billy         sub2
1   2    Amy         sub2  Brain         sub4
2   3  Allen         sub4   Brad         sub3
3   4  Alice         sub6  Bruce         sub6
4   5   Adam         sub5  Betty         sub5

In [297]:
df_left.merge(df_right,on='id')

id Name_x subject_id_x Name_y subject_id_y
0   1   Alex         sub1  Billy         sub2
1   2    Amy         sub2  Brain         sub4
2   3  Allen         sub4   Brad         sub3
3   4  Alice         sub6  Bruce         sub6
4   5   Adam         sub5  Betty         sub5

In [300]:
df_right1.merge(df_left.merge(df_right,on='id'),on='id') #joining more than 2 tables

id   Name subject_id Name_x subject_id_x Name_y subject_id_y
0   1   Cath       sub2   Alex         sub1  Billy         sub2
1   2   Cool       sub1    Amy         sub2  Brain         sub4
2   3  Chris       sub2  Allen         sub4   Brad         sub3
3   4  Crain       sub6  Alice         sub6  Bruce         sub6
4   5   Case       sub3   Adam         sub5  Betty         sub5

In [301]:
df_left.merge(df_right,on=['id','subject_id']) #Default : inner join

id Name_x subject_id Name_y
0   4  Alice       sub6  Bruce
1   5   Adam       sub5  Betty

In [302]:
df_left.merge(df_right,on='subject_id',how='left') #Left join

id_x Name_x subject_id  id_y Name_y
0     1   Alex       sub1   NaN    NaN
1     2    Amy       sub2   1.0  Billy
2     3  Allen       sub4   2.0  Brain
3     4  Alice       sub6   4.0  Bruce
4     5   Adam       sub5   5.0  Betty

In [305]:
df_left.merge(df_right,on='subject_id',how='right') #Right join

id_x Name_x subject_id  id_y Name_y
0   2.0    Amy       sub2     1  Billy
1   3.0  Allen       sub4     2  Brain
2   4.0  Alice       sub6     4  Bruce
3   5.0   Adam       sub5     5  Betty
4   NaN    NaN       sub3     3   Brad

In [307]:
pd.concat([df_left,df_right])

id   Name subject_id
0   1   Alex       sub1
1   2    Amy       sub2
2   3  Allen       sub4
3   4  Alice       sub6
4   5   Adam       sub5
0   1  Billy       sub2
1   2  Brain       sub4
2   3   Brad       sub3
3   4  Bruce       sub6
4   5  Betty       sub5

In [308]:
pd.concat([df_left,df_right],axis=1)

id   Name subject_id  id   Name subject_id
0   1   Alex       sub1   1  Billy       sub2
1   2    Amy       sub2   2  Brain       sub4
2   3  Allen       sub4   3   Brad       sub3
3   4  Alice       sub6   4  Bruce       sub6
4   5   Adam       sub5   5  Betty       sub5

In [313]:
pd.concat([df_left,df_right],axis=1,keys=['left table','right table'])

left table                   right table                  
          id   Name subject_id          id   Name subject_id
0          1   Alex       sub1           1  Billy       sub2
1          2    Amy       sub2           2  Brain       sub4
2          3  Allen       sub4           3   Brad       sub3
3          4  Alice       sub6           4  Bruce       sub6
4          5   Adam       sub5           5  Betty       sub5

In [314]:
pd.concat([df_left,df_right],keys=['left table','right table'])

id   Name subject_id
left table  0   1   Alex       sub1
            1   2    Amy       sub2
            2   3  Allen       sub4
            3   4  Alice       sub6
            4   5   Adam       sub5
right table 0   1  Billy       sub2
            1   2  Brain       sub4
            2   3   Brad       sub3
            3   4  Bruce       sub6
            4   5  Betty       sub5

In [315]:
pd.concat([df_left,df_right],ignore_index=True)

id   Name subject_id
0   1   Alex       sub1
1   2    Amy       sub2
2   3  Allen       sub4
3   4  Alice       sub6
4   5   Adam       sub5
5   1  Billy       sub2
6   2  Brain       sub4
7   3   Brad       sub3
8   4  Bruce       sub6
9   5  Betty       sub5

In [317]:
df_left.append([df_right,df_right1],ignore_index=True)

id   Name subject_id
0    1   Alex       sub1
1    2    Amy       sub2
2    3  Allen       sub4
3    4  Alice       sub6
4    5   Adam       sub5
5    1  Billy       sub2
6    2  Brain       sub4
7    3   Brad       sub3
8    4  Bruce       sub6
9    5  Betty       sub5
10   1   Cath       sub2
11   2   Cool       sub1
12   3  Chris       sub2
13   4  Crain       sub6
14   5   Case       sub3

In [318]:
df_exp=df_left.append([df_right,df_right1],ignore_index=True)
df_exp

id   Name subject_id
0    1   Alex       sub1
1    2    Amy       sub2
2    3  Allen       sub4
3    4  Alice       sub6
4    5   Adam       sub5
5    1  Billy       sub2
6    2  Brain       sub4
7    3   Brad       sub3
8    4  Bruce       sub6
9    5  Betty       sub5
10   1   Cath       sub2
11   2   Cool       sub1
12   3  Chris       sub2
13   4  Crain       sub6
14   5   Case       sub3

In [319]:
df_exp.to_csv('test_output.csv')

In [320]:
import os
os.getcwd()

'C:\\Users\\C.Jacob\\Downloads\\Language_Books\\TestLeaf'

In [324]:
df_read=pd.read_csv('test_output.csv', index_col=0)

'''without index_col=0, it will create its own index
Its better to always include'''

'without index_col=0, it will create its own index\nIts better to always include'

In [325]:
df_read

id   Name subject_id
0    1   Alex       sub1
1    2    Amy       sub2
2    3  Allen       sub4
3    4  Alice       sub6
4    5   Adam       sub5
5    1  Billy       sub2
6    2  Brain       sub4
7    3   Brad       sub3
8    4  Bruce       sub6
9    5  Betty       sub5
10   1   Cath       sub2
11   2   Cool       sub1
12   3  Chris       sub2
13   4  Crain       sub6
14   5   Case       sub3

In [326]:
print(pd.datetime.now())

2019-04-14 12:32:06.329359


In [329]:
pd.to_datetime(pd.Series(['Dec 20, 1991','2019-12-20',None]))

0   1991-12-20
1   2019-12-20
2          NaT
dtype: datetime64[ns]

In [331]:
pd.date_range('1/1/2019',periods=10) #10 days from the date given

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07', '2019-01-08',
               '2019-01-09', '2019-01-10'],
              dtype='datetime64[ns]', freq='D')

In [332]:
pd.date_range('1/1/2019',periods=10, freq='W') #10 week as the frequency is weeks

DatetimeIndex(['2019-01-06', '2019-01-13', '2019-01-20', '2019-01-27',
               '2019-02-03', '2019-02-10', '2019-02-17', '2019-02-24',
               '2019-03-03', '2019-03-10'],
              dtype='datetime64[ns]', freq='W-SUN')

In [333]:
pd.date_range('1/1/2019',periods=10, freq='M') #10 week as the frequency is weeks

DatetimeIndex(['2019-01-31', '2019-02-28', '2019-03-31', '2019-04-30',
               '2019-05-31', '2019-06-30', '2019-07-31', '2019-08-31',
               '2019-09-30', '2019-10-31'],
              dtype='datetime64[ns]', freq='M')

In [339]:
start=pd.datetime(2019,1,1)
end=pd.datetime(2019,2,28)

print(pd.date_range(start,end,freq='W-FRI'))
print(pd.date_range(start,end,freq='M'))

DatetimeIndex(['2019-01-04', '2019-01-11', '2019-01-18', '2019-01-25',
               '2019-02-01', '2019-02-08', '2019-02-15', '2019-02-22'],
              dtype='datetime64[ns]', freq='W-FRI')
DatetimeIndex(['2019-01-31', '2019-02-28'], dtype='datetime64[ns]', freq='M')


In [340]:
pd.date_range?

In [358]:
text=pd.Series(['Data Analyst','@nalytics','Data Science',np.nan,'Exploratory Dara Analysis','Models','1234','Evaluation','Metrics',234 ])
text

0                 Data Analyst
1                    @nalytics
2                 Data Science
3                          NaN
4    Exploratory Dara Analysis
5                       Models
6                         1234
7                   Evaluation
8                      Metrics
9                          234
dtype: object

In [343]:
text.str.lower()

0                 data analyst
1                    @nalytics
2                 data science
3                          NaN
4    exploratory dara analysis
5                       models
6                         1234
7                   evaluation
8                      metrics
dtype: object

In [345]:
text.str.upper()

0                 DATA ANALYST
1                    @NALYTICS
2                 DATA SCIENCE
3                          NaN
4    EXPLORATORY DARA ANALYSIS
5                       MODELS
6                         1234
7                   EVALUATION
8                      METRICS
dtype: object

In [349]:
text.str.len()

0    12.0
1     9.0
2    12.0
3     NaN
4    25.0
5     6.0
6     4.0
7    10.0
8     7.0
dtype: float64

In [350]:
text.str.contains('a') # Returns True if the string has 'a' in it

0     True
1     True
2     True
3      NaN
4     True
5    False
6    False
7     True
8    False
dtype: object

In [352]:
text.str.replace('@','$')

0                 Data Analyst
1                    $nalytics
2                 Data Science
3                          NaN
4    Exploratory Dara Analysis
5                       Models
6                         1234
7                   Evaluation
8                      Metrics
dtype: object

In [353]:
text.str.count('a') #Frequency of the letter 'a'

0    3.0
1    1.0
2    2.0
3    NaN
4    4.0
5    0.0
6    0.0
7    2.0
8    0.0
dtype: float64

In [355]:
text.str.find('n') #Returns the Index of 'n'

0     6.0
1     1.0
2     9.0
3     NaN
4    18.0
5    -1.0
6    -1.0
7     9.0
8    -1.0
dtype: float64

In [356]:
text.str.find('a') 

0    1.0
1    2.0
2    1.0
3    NaN
4    6.0
5   -1.0
6   -1.0
7    2.0
8   -1.0
dtype: float64

In [359]:
text.str.isnumeric()

0    False
1    False
2    False
3      NaN
4    False
5    False
6     True
7    False
8    False
9      NaN
dtype: object